engines:
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: ".eslintrc.yaml"

ratings:
   paths:
   - "**.js"

checks:
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  file-lines:
    config:
      threshold: 1000
  method-lines:
    config:
      threshold: 100
  method-complexity:
    config:
      threshold: 20
