env:
  node: true
  es6: true
  mocha: true
  jquery: true
  browser: true
  es2020: true

plugins: [ haraka ]

extends: [ eslint:recommended, plugin:haraka/recommended ]

root: true

rules:
  indent: [2, 2, { SwitchCase: 1 } ]
  no-unused-vars: ["error", { args: none }]

globals:
  OK: true
  CONT: true
  DENY: true
  DENYSOFT: true
  DENYDISCONNECT: true
  DENYSOFTDISCONNECT: true
