name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master
    permissions:
      contents: read

  prettier:
    uses: haraka/.github/.github/workflows/prettier.yml@master
    permissions:
      contents: write
    secrets: inherit
    with:
      branch: ${{ github.head_ref }}

  coverage:
    uses: haraka/.github/.github/workflows/coverage.yml@master
    permissions:
      contents: read
    secrets: inherit

  ubuntu:
    uses: haraka/.github/.github/workflows/ubuntu.yml@master
    permissions:
      contents: read

  # lacks redis service
  # windows:
  #   uses: haraka/.github/.github/workflows/windows.yml@master

  macos:
    uses: haraka/.github/.github/workflows/macos.yml@master
    permissions:
      contents: read
